server:
  port: 8080
  max-http-request-header-size: 65536

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    web: INFO
    org.springframework.web.socket.messaging: WARN
    org.springframework.boot.web.embedded.tomcat: INFO
    org.springframework.boot.web.context: INFO
    org.springframework.data.repository.config: WARN
    org.hibernate.tool.schema: ERROR
    org.apache.kafka: ERROR
    com.zaxxer.hikari: INFO

spring:
  application:
    name: university-management

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/university?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&sessionVariables=FOREIGN_KEY_CHECKS=0}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}

  jpa:
    open-in-view: false
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

jwt:
  signer-key: ${JWT_SIGNER_KEY:2c0306580240c4c6df087492195a8bd95a8dfa0d646f7c48cf89dbc8621ba226}
  valid-duration: 3600
  refreshable-duration: 360000

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001,http://localhost:5173,http://localhost:4173}